name: ubuntu 16.04
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-16.04]
        python-version: [ 3.6] #,3.7] #,3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
            sudo apt-get update \
            && sudo apt-get install -y \
            python3-pip python3-dev

      - name: install conan
        run: |
          pip install conan
          conan user
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add jinncrafters https://api.bintray.com/conan/jinncrafters/conan

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: build
        env:
          CC: gcc
        run: |
          cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON
          cmake --build . --parallel 2

      #- name: install dependons test
      #  run: pip install -r requirements.txt

      #- name: install kernel
      #  run: jupyter kernelspec install --user kernels/ipython

      #- name: run test
      #  run: ctest #pytest core/rocketjoe/python_sandbox/test_python_kernel.py